apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mongodb
spec:
  selector:
    matchLabels:
      app: nginx-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-mongodb
    spec:
      containers:
        - name: otunbasoa/profile
          image: otunbasoa/profile
          ports:
            - containerPort: 80
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-mongodb
  labels:
    app: nginx-mongodb
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: nginx-mongodb
  type: LoadBalancer
